### ISSUE TITLE
Question about preventing other players from entering the container

### ISSUE THREAD

**Issue by ApolloX939** [TurkeyMcMac/area_containers#2]
I didn't know if you thought of making something like a security manager where you can add people that can enter your container, and also remove them too. (Perhaps have it where if they are inside your container they get "kicked out" as if they clicked the exit)

Another thing on this topic...

Make this per container, so each container can have it's own settings. (Make a checkbox or something like it that can allow all or only those on the list)

**Comment by TurkeyMcMac** [comment]
I've thought about this kind of thing, but I haven't implemented it due to laziness. It seems like quite a complex feature. But you can accomplish something like this with the mod in its current state. See here:

![security](https://user-images.githubusercontent.com/28828704/127211832-84ec8079-d7ce-4dc9-9d67-01a8c73eb16f.png)

Someone who doesn't own the doors in the picture won't be able to break them or pass through unless you give them a key. However, they might be able to break blocks past the doors by holding down left-click, so it's probably a good idea to protect those blocks with a separate protection mod.

I think the mod Protector Redo adds protected doors and whatnot, which might let you do something similar to the above.

**Comment by ApolloX939** [comment]
Ok, yeah right now I think I have a private room where only I can access it thus access to the area containers.

**Comment by ApolloX939** [comment]
Just wanted to know if you had thought about possibly limiting players so they can't access it... then maybe inside the container have a block the owner can access to control the access by other players.

Like how a protector works in Protector Redo when you right click on the protector. (That GUI/formspec where you can add and remove members of the protector)

**Comment by TurkeyMcMac** [comment]
I have thought about it, but I'm lazy. I would like to rely on other mods for auxiliary functionality where possible. Hopefully doing so is possible here. If the protection functionality is something that's absolutely necessary, I can try to implement it.

With the current state of things, you could think of a container as a compact room with no more inherent security than a regular room.

**Comment by ApolloX939** [comment]
Hmm... I wonder if I could make it a separate mod.

Similar to how you do the digilines where if it's there you add a block to the interior that's for the digiline comunications.

Except this one would be placed in one of the walls near the exit (Well that's my guess where we'd want to put it)

Todo:
- [ ] Have a mod which tracks players placing containers (In this case ignore it when the container is teleported via teleporter_tool, and ignore shifting by shifter_tool)
- [ ] Enable some protection where if the player is not allowed to enter, and maybe have a message show in chat to them about it.
- [ ] Have different "modes" ("Private" allows only the owner of the container, "Members Only" allows owner and members in the list, and "Public" allows everyone) for entering (access) and possibly for interaction.

**Comment by TurkeyMcMac** [comment]
Maybe I should add an API to support your mod and others. I won't be able to make code changes for several days, though.

**Comment by TurkeyMcMac** [comment]
@Beanzilla I'm thinking of just biting the bullet and implementing this protection within the mod. Would you be OK with a system that uses locks and keys, similar to the locked chests from Minetest Game?

**Comment by TurkeyMcMac** [comment]
I went ahead and added the feature, so I'll close this issue. You can see locking instructions in the README, on ContentDB, or on the forum post.

**Comment by ApolloX939** [comment]
> @Beanzilla I'm thinking of just biting the bullet and implementing this protection within the mod. Would you be OK with a system that uses locks and keys, similar to the locked chests from Minetest Game?

Nope, I'm fine with that, just wanted some kind of protection so everyone can't just walk into my container.
